### PR TITLE
Make photon and tests running on JDK9

### LINKED ISSUE #274: update lombok or make jdk9 compatible
For our  jdk9 builds we get an error:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.Processor (file:/home/travis/.m2/repository/org/projectlombok/lombok/1.12.6/lombok-1.12.6.jar) to field com.sun.tools.javac.processing.JavacProcessingEnvironment.processorClassLoader
```

### PR DESCRIPTION
**Pull request by karussell**
Fixes #274 

Will revert the version changes of jcommander etc as they do not belong here

### CODE REVIEW

File: src/test/java/de/komoot/photon/ReverseSearchRequestHandlerTest.java [hunk 1]
```diff
@@ -61,11 +52,21 @@ public void testHandle() throws BadRequestException {
         ReverseRequestFactory mockReverseRequestFactory = Mockito.mock(ReverseRequestFactory.class);
         Request mockWebRequest = Mockito.mock(Request.class);
         ReflectionTestUtil.setFieldValue(reverseSearchRequestHandlerUnderTest, ReverseSearchRequestHandler.class, "reverseRequestFactory", mockReverseRequestFactory);
-        ReverseRequestHandlerFactory mockReverseRequestHandlerFactory = Mockito.mock(ReverseRequestHandlerFactory.class);
+
+        SimpleReverseRequestHandler mockSimpleReverseRequestHandler = new SimpleReverseRequestHandler(null) {
```
Comment (karussell) [inline src/test/java/de/komoot/photon/ReverseSearchRequestHandlerTest.java:55]: This does not look prettier but powermockito is really hackish and makes migrating to JDK9 problematic for now as it seems. Furthermore we should create a better test infrastructure where less or zero mocking is necessary.

**Comment by karussell** [comment]
Great hint - will do!
